name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --run

      - name: Build project
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "🔍 Debug: Checking build process results..."
          echo "🔍 Current working directory:"
          pwd
          echo "🔍 Current directory contents:"
          ls -la
          echo "🔍 Checking for common build directories:"
          for dir in "build" "dist" "out" "public"; do
            if [ -d "./$dir" ]; then
              echo "✅ Found ./$dir directory:"
              ls -la "./$dir" || echo "❌ Cannot list contents of ./$dir"
            else
              echo "❌ ./$dir directory does not exist"
            fi
          done
          echo "🔍 Searching for index.html files:"
          find . -name "index.html" -type f 2>/dev/null || echo "❌ No index.html files found"
          echo "🔍 Searching for any HTML files:"
          find . -name "*.html" -type f 2>/dev/null || echo "❌ No HTML files found"

      - name: Validate build artifacts
        run: |
          echo "🔍 Validating build artifacts..."
          echo "🔍 Current directory structure:"
          find . -maxdepth 2 -type d | head -20
          
          # Check which directory actually exists and contains files
          BUILD_DIR=""
          if [ -d "./dist" ] && [ "$(ls -A ./dist 2>/dev/null)" ]; then
            echo "✅ Found dist directory with contents"
            BUILD_DIR="./dist"
          elif [ -d "./build" ] && [ "$(ls -A ./build 2>/dev/null)" ]; then
            echo "✅ Found build directory with contents"
            BUILD_DIR="./build"
          elif [ -d "./out" ] && [ "$(ls -A ./out 2>/dev/null)" ]; then
            echo "✅ Found out directory with contents"
            BUILD_DIR="./out"
          else
            echo "❌ No build output directory found with contents!"
            echo "🔍 Available directories in current path:"
            ls -la
            echo "🔍 Searching for any build-related directories:"
            find . -maxdepth 2 -type d -name "*build*" -o -name "*dist*" -o -name "*out*" 2>/dev/null || echo "No build directories found"
            echo "🔍 Checking package.json for build script:"
            grep -A 5 -B 5 "build" package.json 2>/dev/null || echo "Could not read package.json"
            exit 1
          fi
          
          # Validate index.html exists
          if [ ! -f "$BUILD_DIR/index.html" ]; then
            echo "❌ index.html not found in $BUILD_DIR!"
            echo "🔍 Contents of $BUILD_DIR:"
            ls -la "$BUILD_DIR/"
            echo "🔍 Looking for any HTML files in $BUILD_DIR:"
            find "$BUILD_DIR" -name "*.html" -type f 2>/dev/null || echo "No HTML files found"
            exit 1
          fi
          
          echo "✅ Build artifacts validated successfully"
          echo "📋 Build directory: $BUILD_DIR"
          echo "📋 Build contents:"
          ls -la "$BUILD_DIR/"
          echo "📋 index.html size: $(stat -f%z "$BUILD_DIR/index.html" 2>/dev/null || stat -c%s "$BUILD_DIR/index.html" 2>/dev/null || echo 'unknown') bytes"
          
          # Export build directory for use in deployment steps
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
          echo "SOURCE_PATH=${BUILD_DIR}/*" >> $GITHUB_ENV

      - name: Set deployment target based on branch
        id: deployment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "target_dir=${{ secrets.SFTP_REMOTE_DIR_PROD }}" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "target_dir=${{ secrets.SFTP_REMOTE_DIR_DEV }}" >> $GITHUB_OUTPUT
            echo "environment=development" >> $GITHUB_OUTPUT
          fi

      - name: Verify deployment configuration
        run: |
          echo "🔍 Verifying deployment configuration..."
          echo "Branch: ${{ github.ref }}"
          echo "Environment: ${{ steps.deployment.outputs.environment }}"
          echo "Target directory: ${{ steps.deployment.outputs.target_dir }}"
          
          # Check if required secrets are available (without exposing values)
          if [ -z "${{ secrets.SFTP_HOST }}" ]; then
            echo "❌ SFTP_HOST secret is missing"
            exit 1
          else
            echo "✅ SFTP_HOST is configured"
          fi
          
          if [ -z "${{ secrets.SFTP_USER }}" ]; then
            echo "❌ SFTP_USER secret is missing"
            exit 1
          else
            echo "✅ SFTP_USER is configured"
          fi
          
          if [ -z "${{ secrets.SFTP_PASS }}" ]; then
            echo "❌ SFTP_PASS secret is missing"
            exit 1
          else
            echo "✅ SFTP_PASS is configured"
          fi
          
          if [ -z "${{ secrets.SFTP_PORT }}" ]; then
            echo "❌ SFTP_PORT secret is missing"
            exit 1
          else
            echo "✅ SFTP_PORT is configured"
          fi
          
          if [ -z "${{ steps.deployment.outputs.target_dir }}" ]; then
            echo "❌ Target directory not set for this branch"
            exit 1
          else
            echo "✅ Target directory is configured"
          fi

      - name: Test SSH Connection
        run: echo "🔍 Testing SSH connection to deployment server..."
        
      - name: Verify SSH Authentication
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "✅ SSH Authentication successful!"
            echo "🔍 Server information:"
            echo "  - Hostname: $(hostname)"
            echo "  - User: $(whoami)"
            echo "  - Current directory: $(pwd)"
            echo "  - Available space: $(df -h . | tail -1 | awk '{print $4}')"

      - name: Create target directory via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            mkdir -p ${{ steps.deployment.outputs.target_dir }}
            chmod 755 ${{ steps.deployment.outputs.target_dir }}

      - name: Deploy to SFTP (${{ steps.deployment.outputs.environment }})
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          source: "${{ env.SOURCE_PATH }}"
          target: ${{ steps.deployment.outputs.target_dir }}
          strip_components: 1
          overwrite: true
          rm: true

      - name: Cleanup and set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            find ${{ steps.deployment.outputs.target_dir }} -type f -name "*.html" -exec chmod 644 {} \;
            find ${{ steps.deployment.outputs.target_dir }} -type f -name "*.js" -exec chmod 644 {} \;
            find ${{ steps.deployment.outputs.target_dir }} -type f -name "*.css" -exec chmod 644 {} \;
            find ${{ steps.deployment.outputs.target_dir }} -type d -exec chmod 755 {} \;

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "🔍 Verifying deployment in: ${{ steps.deployment.outputs.target_dir }}"
            ls -la "${{ steps.deployment.outputs.target_dir }}"
            if [ -f "${{ steps.deployment.outputs.target_dir }}/index.html" ]; then
              echo "✅ Deployment successful - index.html found"
            else
              echo "❌ Deployment failed - index.html not found"
              exit 1
            fi

      - name: Deployment success notification
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Environment: ${{ steps.deployment.outputs.environment }}"
          echo "Target directory: ${{ steps.deployment.outputs.target_dir }}"
          echo "Build directory used: ${{ env.BUILD_DIR }}"
